### ISSUE TITLE
Smart Hub immediately loose connection

### ISSUE THREAD

**Issue by Skefflock** [dtschan/scratch2-wedo2#1]
Hello, Daniel
On my trying to start the extension I got this. It does keep connection via xfce bluetooth manager and does work under virtual machine running win8 on in VirtualBox.
Don't know if I'm doing anything wrong. See no other way to ask for some help.
Thank you.

bluetoothctl
[NEW] Device A0:E6:F8:20:53:3C LPF2 Smart Hub 2 I/O

sudo ./scratch-wedo2.py A0:E6:F8:20:53:3C

Traceback (most recent call last):
  File "./scratch-wedo2.py", line 135, in <module>
    req.write_without_response_by_handle(HANDLE_CCC_BUTTON, pack("<h", 0x0001))
AttributeError: 'Requester' object has no attribute 'write_without_response_by_handle'

**Comment by dtschan** [comment]
Hi Skefflock

Does anything change if you replace `gattlib` with `git+https://github.com/matthewelse/pygattlib` in `requirements.txt` and upgrade the python dependencies with: `pip install -r requirements.txt`?

Kind regards
    Daniel

**Comment by Skefflock** [comment]
Hi again Daniel
No. Nothing change

requirements.txt
git+https://github.com/matthewelse/pygattlib
flask

$ pip install -r requirements.txt
Collecting git+https://github.com/matthewelse/pygattlib (from -r
requirements.txt (line 1))
  Cloning https://github.com/matthewelse/pygattlib to /tmp/pip-mGFVuG-build
  Requirement already satisfied (use --upgrade to upgrade):
gattlib==0.20150805 from git+https://github.com/matthewelse/pygattlib in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: flask in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: itsdangerous>=0.21 in
/usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt
(line 2))
Requirement already satisfied: click>=2.0 in
/usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt
(line 2))
Requirement already satisfied: Werkzeug>=0.7 in
/usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt
(line 2))
Requirement already satisfied: Jinja2>=2.4 in
/usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt
(line 2))
Requirement already satisfied: MarkupSafe>=0.23 in
/usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->flask->-r
requirements.txt (line 2))

but I still got

sudo ./scratch-wedo2.py A0:E6:F8:20:53:3C
Traceback (most recent call last):
  File "./scratch-wedo2.py", line 135, in <module>
    req.write_without_response_by_handle(HANDLE_CCC_BUTTON, pack("<h",
0x0001))
AttributeError: 'Requester' object has no attribute
'write_without_response_by_handle'



2017-10-28 16:43 GMT+02:00 Daniel Tschan <notifications@github.com>:

**Comment by Skefflock** [comment]
Hi, Daniel.
Yes that works.
Thanks for help and good work.
